FROM apache/airflow:2.8.1-python3.10

USER root
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements.txt /opt/airflow/requirements.txt
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt

ENV PYTHONPATH="/opt/airflow:/opt/airflow/dags:/opt/airflow/scripts:${PYTHONPATH}"

WORKDIR /opt/airflow
